# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Run OpenSCAP ANSSI BP28 High remediation
  ansible.builtin.command:
    cmd: >
      oscap xccdf eval
      --remediate
      --fetch-remote-resources
      --results /tmp/oscap-results.xml
      --report /tmp/oscap-report.html
      --profile {{ configure_hardening_oscap_profile }}
      {% if configure_hardening_oscap_tailoring_file | length > 0 %}
      --tailoring-file {{ configure_hardening_oscap_tailoring_file }}
      {% endif %}
      {{ configure_hardening_oscap_ds_file }}
  register: oscap_remediation
  failed_when: oscap_remediation.rc not in [0, 2]
  changed_when: oscap_remediation.rc == 2
  when:
    - not revert
    - ansible_distribution == "SLES"
